/*
 * Implementation of the bottom-screen UI declared in bottom_ui.h.
 *
 * Rendering runs on its own background thread rather than being called
 * from the main thread's idle moments: Lynx's startup (reading its config,
 * history, etc.) runs synchronously on the main thread for a while before
 * it ever reaches the input-polling loop that would otherwise be the only
 * place driving this, and the bottom screen is double-buffered -- a
 * single render (or long gaps between them) leaves the two buffers out of
 * sync, which is exactly what showed up as flicker. A dedicated thread
 * keeps presenting every vblank for the whole life of the app, completely
 * independent of whatever Lynx/the top screen is doing.
 */
#include <bottom_ui.h>
#include <bookmarks.h>
#include <image_preview.h>
#include <font_render.h>
#include <citro2d.h>
#include <math.h>

#include "bottom_ui_t3x.h"	/* generated by tex3ds+bin2o from gfx/bottom_ui.t3s */


#define FADE_PERIOD_MS 10000.0	/* one full fade in+out cycle */
#define FADE_MIN 0.25f		/* never fade all the way to invisible */
#define FADE_MAX 1.0f
#define RENDER_THREAD_STACK_SIZE (4 * 1024)

/* Bottom-screen horizontal scroll state. Written by the input handling
 * (see platform_3ds.c) and read here when drawing the scrollbar. These
 * definitions provide the storage that the `extern` declarations in the
 * headers refer to; without them the link step fails with
 * "undefined reference to LY3DS_scroll_x / LY3DS_max_scroll_x". */
int LY3DS_scroll_x = 0;
int LY3DS_max_scroll_x = 0;

static C2D_SpriteSheet sheet;
static C2D_Image img_bg, img_fg;
static C3D_RenderTarget *bottom_target;
static bool ready = false;
static u64 start_ms;
static Thread render_thread;

void bottom_ui_draw_content(float alpha_mul)
{
    double elapsed = (double) (osGetTime() - start_ms);
    float phase = (float) fmod(elapsed, FADE_PERIOD_MS) / (float) FADE_PERIOD_MS;
    float wave = (sinf(phase * 2.0f * (float) M_PI) + 1.0f) * 0.5f;	/* 0..1 */
    float fg_alpha = (FADE_MIN + wave * (FADE_MAX - FADE_MIN)) * alpha_mul;
    C2D_ImageTint bg_tint, fg_tint;

    C2D_AlphaImageTint(&bg_tint, alpha_mul);
    C2D_AlphaImageTint(&fg_tint, fg_alpha);
    C2D_DrawImageAt(img_bg, 0, 0, 0, &bg_tint, 1.0f, 1.0f);
    C2D_DrawImageAt(img_fg, 0, 0, 0.5f, &fg_tint, 1.0f, 1.0f);

    /* Horizontal scrollbar overlaid on the content. */
    font_draw_scrollbar_bottom(LY3DS_scroll_x, LY3DS_max_scroll_x);
}

static void bottom_ui_render_once(void)
{
    C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
    C2D_TargetClear(bottom_target, C2D_Color32(0, 0, 0, 255));
    C2D_SceneBegin(bottom_target);
    bottom_ui_draw_content(1.0f);
    C3D_FrameEnd(0);
}

static void bottom_ui_thread_main(void *arg)
{
    (void) arg;
    while (ready) {
	if (bookmarks_is_open())
	    bookmarks_render_bottom(bottom_target);
	else if (image_preview_is_active())
	    image_preview_render_bottom(bottom_target);
	else
	    bottom_ui_render_once();
	gspWaitForVBlank();
    }
}

void bottom_ui_init(void)
{
    C3D_Init(C3D_DEFAULT_CMDBUF_SIZE);
    C2D_Init(C2D_DEFAULT_MAX_OBJECTS);
    C2D_Prepare();

    bottom_target = C2D_CreateScreenTarget(GFX_BOTTOM, GFX_LEFT);

    sheet = C2D_SpriteSheetLoadFromMem(bottom_ui_t3x, bottom_ui_t3x_size);
    if (sheet == NULL)
	return;
    img_bg = C2D_SpriteSheetGetImage(sheet, 0);	/* bottom-bg.png */
    img_fg = C2D_SpriteSheetGetImage(sheet, 1);	/* bottom-guide-fg.png */

    start_ms = osGetTime();
    ready = true;

    render_thread = threadCreate(bottom_ui_thread_main, NULL,
				  RENDER_THREAD_STACK_SIZE, 0x30, -1, false);
}
